"""v3

Revision ID: 34039c88ce97
Revises: 70f6c6551f92
Create Date: 2022-02-10 15:29:59.348116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34039c88ce97'
down_revision = '70f6c6551f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('pageViews', sa.String(length=10), nullable=False),
    sa.Column('price', sa.String(length=25), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    # ### end Alembic commands ###
