"""v2

Revision ID: 70f6c6551f92
Revises: ea937f8dea77
Create Date: 2022-02-09 17:18:53.300903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f6c6551f92'
down_revision = 'ea937f8dea77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('facebook', sa.String(length=25), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_users')
    # ### end Alembic commands ###
