"""v1

Revision ID: ea937f8dea77
Revises: 
Create Date: 2022-02-08 14:54:03.738035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea937f8dea77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=250), nullable=False),
    sa.Column('permission', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=250), nullable=False),
    sa.Column('login_time', sa.DATETIME(timezone=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('update_time', sa.DateTime(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('no', sa.String(length=50), nullable=False),
    sa.Column('_type', sa.String(length=50), nullable=False),
    sa.Column('cover_img', sa.String(length=100), nullable=False),
    sa.Column('detail_img', sa.String(length=100), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('product_list', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('update_user_id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('no', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cover_img', sa.String(length=100), nullable=False),
    sa.Column('detail_img', sa.String(length=100), nullable=False),
    sa.Column('description_img', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('in_price', sa.Integer(), nullable=False),
    sa.Column('out_price', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('package_list', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('update_user_id', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('no')
    )
    op.create_table('tests',
    sa.Column('is_delete', sa.BOOLEAN(), nullable=True),
    sa.Column('create_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('update_time', sa.DATETIME(timezone=6), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('products')
    op.drop_table('packages')
    op.drop_table('logs')
    op.drop_table('classifications')
    op.drop_table('admin_users')
    op.drop_table('admin_roles')
    # ### end Alembic commands ###
